// Transcripts via the UNDOCUMENTED timedtext endpoint.
//
// Why this file is not built on the official API, stated plainly because the tool
// output repeats it to every caller:
//
//   captions.download, per Google's own reference: "This method is requires the
//   user to have permission to edit the video." Quota cost 200 units.
//
// So the official path returns transcripts for YOUR videos only. Researching other
// people's content — which is the entire purpose of this asset — cannot use it.
// The chosen fallback is the endpoint the youtube-transcript libraries use: read
// the watch page, pull the caption-track URLs out of the embedded player response,
// fetch a track directly. It costs zero API quota because it is not the API.
//
// The honest ledger on this choice:
//   - It is outside YouTube's Terms of Service.
//   - It is undocumented, therefore unversioned, therefore it breaks without notice.
//     It has broken repeatedly in the past and will again.
//   - It returns nothing when captions are disabled, and auto-generated captions
//     are speech-to-text with real error rates on names, jargon and accents.
//   - It must never be cited as a primary source.
// Every response from this module leads with that, so a transcript can never be
// laundered into evidence by a caller who did not read this file.
import { buildUrl, fetchText, fetchJson, explainGoogleError } from "./http.js";
import { readCache, writeCache, cacheKey, freshnessNote } from "./cache.js";
import { accessToken, oauthConfig } from "./oauth.js";
import { reserve } from "./quota.js";

export const UNOFFICIAL_NOTICE =
  "UNOFFICIAL SOURCE: fetched from YouTube's undocumented timedtext endpoint, NOT the YouTube Data API. " +
  "The official captions.download requires edit permission on the video, so it cannot serve third-party " +
  "research. This path is outside YouTube's ToS, is unversioned and may break without notice, and returns " +
  "nothing when captions are off. Auto-generated captions are speech-to-text and misrender names, jargon " +
  "and accented speech. Do not cite as a primary source.";

export interface TranscriptResult {
  videoId: string;
  language: string;
  autoGenerated: boolean;
  text: string;
  wordCount: number;
  segments: number;
  freshness: string;
  /** True when this came from the OFFICIAL captions.download (owned video, OAuth). */
  official?: boolean;
}

interface CaptionTrack {
  baseUrl?: string;
  languageCode?: string;
  kind?: string; // "asr" for auto-generated
  name?: { simpleText?: string };
}

/** Pull the videoId out of an id, a watch URL, a youtu.be link or a Shorts URL. */
export function normalizeVideoId(input: string): string | undefined {
  const s = String(input ?? "").trim();
  if (!s) return undefined;
  if (/^[\w-]{11}$/.test(s)) return s;
  try {
    const u = new URL(s.startsWith("http") ? s : `https://${s}`);
    if (u.hostname.endsWith("youtu.be")) {
      const id = u.pathname.replace(/^\/+/, "").split("/")[0];
      return /^[\w-]{11}$/.test(id) ? id : undefined;
    }
    const v = u.searchParams.get("v");
    if (v && /^[\w-]{11}$/.test(v)) return v;
    const m = /\/(shorts|embed|live|v)\/([\w-]{11})/.exec(u.pathname);
    if (m) return m[2];
  } catch {
    /* not a URL */
  }
  return undefined;
}

/** Extract the caption track list from a watch page's embedded player response. */
export function extractCaptionTracks(html: string): CaptionTrack[] {
  // The player response is a JSON blob assigned in a <script>. Rather than
  // brace-matching the whole object (fragile), locate the captionTracks array and
  // bracket-match just that, which is a much smaller and better-behaved target.
  const marker = '"captionTracks":';
  const at = html.indexOf(marker);
  if (at === -1) return [];
  const start = html.indexOf("[", at);
  if (start === -1) return [];

  let depth = 0;
  let inStr = false;
  let esc = false;
  let end = -1;
  for (let i = start; i < html.length; i++) {
    const c = html[i];
    if (inStr) {
      if (esc) esc = false;
      else if (c === "\\") esc = true;
      else if (c === '"') inStr = false;
      continue;
    }
    if (c === '"') inStr = true;
    else if (c === "[") depth++;
    else if (c === "]") {
      depth--;
      if (depth === 0) {
        end = i + 1;
        break;
      }
    }
  }
  if (end === -1) return [];

  try {
    return JSON.parse(html.slice(start, end)) as CaptionTrack[];
  } catch {
    return [];
  }
}

/** Decode the XML entities that the timedtext XML format uses. */
export function decodeEntities(s: string): string {
  return s
    .replace(/&amp;/g, "&")
    .replace(/&lt;/g, "<")
    .replace(/&gt;/g, ">")
    .replace(/&quot;/g, '"')
    .replace(/&#39;/g, "'")
    .replace(/&apos;/g, "'")
    .replace(/&#(\d+);/g, (_, d) => String.fromCodePoint(Number(d)));
}

interface Json3 {
  events?: Array<{ segs?: Array<{ utf8?: string }> }>;
}

/** Parse either json3 or the legacy XML timedtext payload into plain text. */
export function parseTimedText(body: string): { text: string; segments: number } {
  const trimmed = body.trim();
  if (trimmed.startsWith("{")) {
    try {
      const j = JSON.parse(trimmed) as Json3;
      const parts: string[] = [];
      for (const ev of j.events ?? []) {
        for (const seg of ev.segs ?? []) {
          if (seg.utf8) parts.push(seg.utf8);
        }
      }
      const text = parts.join("").replace(/\n+/g, " ").replace(/\s{2,}/g, " ").trim();
      return { text, segments: (j.events ?? []).length };
    } catch {
      /* fall through to XML */
    }
  }
  const segs = [...trimmed.matchAll(/<text[^>]*>([\s\S]*?)<\/text>/g)].map((m) => decodeEntities(m[1]).replace(/\s+/g, " ").trim());
  return { text: segs.join(" ").replace(/\s{2,}/g, " ").trim(), segments: segs.length };
}

// ---------------------------------------------------------------------------
// OFFICIAL path — captions.list + captions.download. Works ONLY on videos the
// authenticated account has edit permission for, which in practice means the
// user's own channel. Added after live testing showed the unofficial path is
// currently blocked (see BLOCKED_NOTICE): for owned videos this is compliant,
// stable, and needs no caveats at all. Costs 50 units to list + 200 to download
// against the 10,000/day pool.
// ---------------------------------------------------------------------------

interface RawCaptionList {
  items?: Array<{ id?: string; snippet?: { language?: string; trackKind?: string; name?: string } }>;
}

export async function officialTranscript(videoId: string, preferLang?: string): Promise<TranscriptResult | undefined> {
  const cfg = oauthConfig();
  if (!cfg) return undefined;

  const token = await accessToken(cfg);
  const listRes = reserve("captions.list");
  if (!listRes.ok) throw new Error(listRes.reason);

  let list: RawCaptionList;
  try {
    list = await fetchJson<RawCaptionList>(
      buildUrl("https://www.googleapis.com/youtube/v3/", "captions", { part: "snippet", videoId }),
      { headers: { Authorization: `Bearer ${token}` } }
    );
  } catch (err) {
    // 403 here is the ownership wall, and it is EXPECTED for third-party videos.
    // Returning undefined lets the caller fall through to the unofficial path
    // instead of surfacing an alarming permissions error for a normal case.
    return undefined;
  }

  const items = list.items ?? [];
  if (!items.length) return undefined;

  const pick =
    (preferLang ? items.find((i) => i.snippet?.language === preferLang) : undefined) ??
    items.find((i) => i.snippet?.language?.startsWith("en")) ??
    items[0];
  if (!pick?.id) return undefined;

  const dlRes = reserve("captions.download");
  if (!dlRes.ok) throw new Error(dlRes.reason);

  let body: string;
  try {
    body = await fetchText(
      buildUrl("https://www.googleapis.com/youtube/v3/", `captions/${encodeURIComponent(pick.id)}`, { tfmt: "srt" }),
      { headers: { Authorization: `Bearer ${token}` } }
    );
  } catch (err) {
    throw new Error(`official captions.download failed: ${explainGoogleError(err)}`);
  }

  // SRT: strip index lines and timecodes, keep the text.
  const text = body
    .replace(/\r/g, "")
    .split("\n")
    .filter((l) => l.trim() && !/^\d+$/.test(l.trim()) && !/^\d{2}:\d{2}:\d{2}[.,]\d{3}\s*-->/.test(l))
    .join(" ")
    .replace(/\s{2,}/g, " ")
    .trim();
  if (!text) return undefined;

  return {
    videoId,
    language: pick.snippet?.language ?? "unknown",
    autoGenerated: pick.snippet?.trackKind === "ASR",
    text,
    wordCount: text.split(/\s+/).filter(Boolean).length,
    segments: 0,
    freshness: freshnessNote(undefined),
    official: true,
  };
}

/** What the unofficial endpoint is actually doing as of 2026-07-29, measured. */
export const BLOCKED_NOTICE =
  "The unofficial timedtext endpoint returned HTTP 200 with a ZERO-BYTE body. That is not a missing-captions " +
  "case and not a format change — the caption tracks ARE listed on the watch page and the signed URL is intact. " +
  "It is YouTube actively blocking un-attested caption fetches (the /youtubei/v1/player endpoint answers " +
  "UNPLAYABLE / \"The page needs to be reloaded\" for the same video, which is the bot-check wall). Getting past " +
  "it requires forging a proof-of-origin token, i.e. defeating an access control, which this server will not do.\n" +
  "WHAT WORKS INSTEAD:\n" +
  "  - Videos on a channel you OWN: configure OAuth (npm --prefix youtube-mcp run setup:oauth). This tool then " +
  "uses the OFFICIAL captions.download, which is compliant, stable and carries none of these caveats.\n" +
  "  - Third-party videos: youtube_get_comments + youtube_analyze_topics infer subject matter without a " +
  "transcript. Weaker, and honestly labelled as inference.";

export async function getTranscript(rawId: string, preferLang?: string, fresh = false): Promise<TranscriptResult> {
  const videoId = normalizeVideoId(rawId);
  if (!videoId) {
    throw new Error(`"${rawId}" is not a recognisable video id or URL. Expected an 11-character id, or a watch/youtu.be/shorts URL.`);
  }

  const key = cacheKey("transcript", { videoId, preferLang: preferLang ?? "" });
  if (!fresh) {
    const hit = readCache<TranscriptResult>("transcript", key);
    if (hit) return { ...hit.payload, freshness: freshnessNote(hit) };
  }

  // OFFICIAL FIRST when OAuth is available. For a video the user owns this is
  // compliant and stable, so there is no reason to prefer the scraped path; it
  // returns undefined (not throws) when the video isn't ours, which is the
  // normal third-party case.
  if (oauthConfig()) {
    try {
      const official = await officialTranscript(videoId, preferLang);
      if (official) {
        writeCache("transcript", key, official);
        return official;
      }
    } catch (err) {
      // A real failure (quota, revoked token) is worth surfacing rather than
      // silently degrading to a path we know is currently blocked.
      throw err;
    }
  }

  const watchUrl = buildUrl("https://www.youtube.com/", "watch", { v: videoId, hl: "en" });
  const html = await fetchText(watchUrl, { maxBytes: 4_000_000 });

  const tracks = extractCaptionTracks(html);
  if (!tracks.length) {
    throw new Error(
      `No caption tracks found for ${videoId}. Either the uploader disabled captions, or YouTube served a ` +
        `consent/bot-check page instead of the watch page, or the undocumented endpoint changed shape. ` +
        `There is no official fallback: captions.download needs edit permission on the video. ` +
        `Workaround: youtube_get_comments + youtube_analyze_topics infer subject matter without a transcript.`
    );
  }

  const pick =
    (preferLang ? tracks.find((t) => t.languageCode === preferLang) : undefined) ??
    tracks.find((t) => t.languageCode?.startsWith("en")) ??
    tracks[0];
  if (!pick?.baseUrl) throw new Error(`Caption track for ${videoId} has no fetchable URL.`);

  // Request json3 — more robust to parse than the legacy XML.
  const trackUrl = new URL(pick.baseUrl.replace(/\\u0026/g, "&"));
  trackUrl.searchParams.set("fmt", "json3");
  const body = await fetchText(trackUrl, { maxBytes: 4_000_000 });
  const { text, segments } = parseTimedText(body);

  if (!text) {
    // The original message here guessed "the format likely changed", which sent
    // the reader looking for a parser bug. Live testing showed the body is
    // literally zero bytes, so name the actual cause.
    const detail = body.length === 0 ? "Response body was 0 bytes." : `Body was ${body.length} bytes but parsed to no text.`;
    throw new Error(
      `No transcript for ${videoId}. ${detail} ${tracks.length} caption track(s) ARE listed ` +
        `(${tracks.map((t) => t.languageCode ?? "?").join(", ")}), so captions exist and are not the problem.\n\n${BLOCKED_NOTICE}`
    );
  }

  const result: TranscriptResult = {
    videoId,
    language: pick.languageCode ?? "unknown",
    autoGenerated: pick.kind === "asr",
    text,
    wordCount: text.split(/\s+/).filter(Boolean).length,
    segments,
    freshness: freshnessNote(undefined),
  };
  writeCache("transcript", key, result);
  return result;
}
